#382 - graceful error handling for unexpected or unhandled errors (#383)
Sending a PR to handle previously unhandled errors that are outside of missing UI elements, error-handling during step and integrations execution, unrecognizable steps, missing parameters etc.

An example would be referencing a variable that is not yet declared -
```
ReferenceError: Can't find variable: abc
  /Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/phantomjs:/code/demo.js:1386
  /Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/phantomjs:/platform/casper.js:1685 in runStep
  /Users/kensoh/Cloud Drive/Marketing/Website/api/tagui/src/phantomjs:/platform/casper.js:414 in checkStep
```

---

With this PR, the following standard error message from TagUI will be displayed instead -
```
ERROR - can't find variable: b
```